### ISSUE TITLE
Allow to copy unicode instead name of it

### ISSUE THREAD

**Issue by egoist** [egoist/emoji#3]
eg: 💯 not `:100:`

**Comment by NekR** [comment]
Why does it copy `:100:` in the first place?

**Comment by egoist** [comment]
@NekR to use in git commit message, guess github won't the unicode version?

**Comment by Phantr4x** [comment]
Nop, it works. 😂

**Comment by NekR** [comment]
I think whatever works on GitHub, it most likely normalizes emoji with some lib (I believe they even open sourced it).

**Comment by egoist** [comment]
Hmm, somehow the last time I used emoji in commit message it doesn't work as expect 😕 We can make it *copy unicode* by default then

**Comment by NekR** [comment]
@egoist need to test for sure though, but if @Phantr4x says it works then probably it works.

**Comment by egoist** [comment]
Done.
