### ISSUE TITLE
Add some keywords for each emoji

### ISSUE THREAD

**Issue by Phantr4x** [egoist/emoji#4]
eg: 😄 => `['face', 'smile', 'happy', 'joy', ':D', 'grin']`

More: [emojilib](https://github.com/muan/emojilib)

**Comment by egoist** [comment]
是要显示出来？

**Comment by Phantr4x** [comment]
应该显示不下，如果做到 tooltip 里也许可行

**Comment by egoist** [comment]
已经加到搜索里的啊

**Comment by Phantr4x** [comment]
😂 没发现，无视我这条 issue 吧
