### ISSUE TITLE
Autofocus

### ISSUE THREAD

**Issue by IonicaBizau** [egoist/emoji#6]
Autofocus the input, so I don't have to press <kbd>Tab</kbd> or click. :grin:

**Comment by egoist** [comment]
Should be fixed, you might need to manually clear site data.

![2018-01-19 6 59 10](https://user-images.githubusercontent.com/8784712/35147811-e7e6d37c-fd4a-11e7-9e85-6e7551445bb6.png)

**Comment by IonicaBizau** [comment]
Thanks, it just worked. :grin:
